export enum Groups {
    AnimalsAndNature = 'animals-nature',
    SmileysAndEmotion = 'smileys-emotion',
    FoodAndDrink = 'food-drink',
    TravelAndPlaces = 'travel-places',
    Activities = 'activities',
    Objects = 'objects',
    Symbols = 'symbols',
    Flags = 'flags',
}

export enum Subgroups {
    FaceSmiling = 'face-smiling',
    FaceAffection = 'face-affection',
    FaceTongue = 'face-tongue',
    FaceHand = 'face-hand',
    FaceNeutralSkeptical = 'face-neutral-skeptical',
    FaceSleepy = 'face-sleepy',
    FaceUnwell = 'face-unwell',
    FaceHat = 'face-hat',
    FaceGlasses = 'face-glasses',
    FaceConcerned = 'face-concerned',
    FaceNegative = 'face-negative',
    FaceCostume = 'face-costume',
    CatFace = 'cat-face',
    MonkeyFace = 'monkey-face',
    Emotion = 'emotion',
    HandFingersOpen = 'hand-fingers-open',
    HandFingersPartial = 'hand-fingers-partial',
    HandSingleFinger = 'hand-single-finger',
    HandFingersClosed = 'hand-fingers-closed',
    Hands = 'hands',
    HandProp = 'hand-prop',
    BodyParts = 'body-parts',
    Person = 'person',
    PersonGesture = 'person-gesture',
    PersonRole = 'person-role',
    PersonFantasy = 'person-fantasy',
    PersonActivity = 'person-activity',
    PersonSport = 'person-sport',
    PersonResting = 'person-resting',
    Family = 'family',
    PersonSymbol = 'person-symbol',
    HairStyle = 'hair-style',
    AnimalMammal = 'animal-mammal',
    AnimalBird = 'animal-bird',
    AnimalAmphibian = 'animal-amphibian',
    AnimalReptile = 'animal-reptile',
    AnimalMarine = 'animal-marine',
    AnimalBug = 'animal-bug',
    PlantFlower = 'plant-flower',
    PlantOther = 'plant-other',
    FoodFruit = 'food-fruit',
    FoodVegetable = 'food-vegetable',
    FoodPrepared = 'food-prepared',
    FoodAsian = 'food-asian',
    FoodMarine = 'food-marine',
    FoodSweet = 'food-sweet',
    Drink = 'drink',
    Dishware = 'dishware',
    PlaceMap = 'place-map',
    PlaceGeographic = 'place-geographic',
    PlaceBuilding = 'place-building',
    PlaceReligious = 'place-religious',
    PlaceOther = 'place-other',
    TransportGround = 'transport-ground',
    TransportWater = 'transport-water',
    TransportAir = 'transport-air',
    Hotel = 'hotel',
    Time = 'time',
    SkyWeather = 'sky-weather',
    Event = 'event',
    AwardMedal = 'award-medal',
    Sport = 'sport',
    Game = 'game',
    ArtsCrafts = 'arts-crafts',
    Clothing = 'clothing',
    Sound = 'sound',
    Music = 'music',
    MusicalInstrument = 'musical-instrument',
    Phone = 'phone',
    Computer = 'computer',
    LightVideo = 'light-video',
    BookPaper = 'book-paper',
    Money = 'money',
    Mail = 'mail',
    Writing = 'writing',
    Office = 'office',
    Lock = 'lock',
    Tool = 'tool',
    Science = 'science',
    Medical = 'medical',
    Household = 'household',
    OtherObject = 'other-object',
    TransportSign = 'transport-sign',
    Warning = 'warning',
    Arrow = 'arrow',
    Religion = 'religion',
    Zodiac = 'zodiac',
    AvSymbol = 'av-symbol',
    Gender = 'gender',
    OtherSymbol = 'other-symbol',
    Keycap = 'keycap',
    Alphanum = 'alphanum',
    Geometric = 'geometric',
    Flag = 'flag',
}

export type Group = `${Groups}`;

export type Subgroup = `${Subgroups}`;

export interface Emoji {
    char: string
    keywords: string[]
    name: string
    group: string
    subgroup: string
    hexcode: string
}